on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: false
        default: 'samrat'

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo " Hello!!! ${{github.event.inputs.name}}"
